Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'
Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'
Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'
Metrics/MethodLength:
  Enabled: false