version: '3.8'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/portfolio
      - uploads-volume:/portfolio/public/uploads
    ports:
      - "3001:3001"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"

volumes:
  db-volume:
  uploads-volume:
